### ISSUE TITLE
Something is not working in the notebook

### ISSUE THREAD

**Issue by pligor** [dokato/dfa#1]
![screenshot-localhost-8888-2017-06-13-09-51-15](https://user-images.githubusercontent.com/1448173/27074117-0e4e88f0-501e-11e7-9767-1c56206b8e68.png)
As you can see in the image something is wrong in the notebook

**Comment by dokato** [comment]
Thank you @pligor for pointing this out. It seems that sometimes an ending index of the artefact exceeded signal's length. (Not surprising if it comes from a Gaussian distribution)
I fixed that and added python3 support for this notebook. Please pull and check.

**Comment by dokato** [comment]
Due to inactivity I assume it's solved.
