### ISSUE TITLE
An issue

### ISSUE THREAD

**Issue by kderakhshani** [dokato/dfa#3]
Dear dokato,

Thank you for your code.

line 75                  fluct[e] = np.mean(np.sqrt(calc_rms(y, sc)**2))
makes no sense. I think:
                             fluct[e] = np.mean(calc_rms(y, sc))
would be enough.

Am I right? Or maybe it is a programming trick?

Best regards,

Kamran  Derakhshani

**Comment by dokato** [comment]
whoopsss... Looks like you're absolutely right. The order of mean and sqrt is reversed. It should be obviously: `np.sqrt(np.mean(calc_rms(y, sc)**2))`. Strangely, it doesn't seem to have a critical impact on estimated values. Probably for the length of time series I tested it on, it doesn't matter as much. 
Anyway, thanks @kderakhshani for a nice spot!
I fixed it already.

**Comment by kderakhshani** [comment]
Dear Dokata,
Thank you for your email.
 
Please note that  the Fluctuation Function F(N) is just a mean of RMS's for each scale (window length). It is not an 
RMS of RMS's ! (cf. Hardstone, et al, 2012,  p. 6)
So, your code was incidentally calculating F(N) CORRECTLY!
Just the np.sqrt()  and **2  should have been deleted, like:                                                                             fluct[e] = np.mean(calc_rms(y, sc))

This is faster, too.

Best,
Kamran

    On Monday, July 22, 2019, 4:29:29 PM GMT+2, dokato <notifications@github.com> wrote:  
 
 
Upsss... Looks like you're absolutely right. The order of mean and sqrt is reversed. It should be obviously: np.sqrt(np.mean(calc_rms(y, sc)**2)). Strangely, it doesn't seem to have a critical impact on estimated values. Probably for the length of time series I tested it on, it doesn't matter as much.
Anyway, thanks @kderakhshani for a nice spot!
I fixed it already.

**Comment by dokato** [comment]
Not necessarily, looks like there's no agreement between Hardstone and Ihlan paper than I was relying my implementation on. If you have a look at their `Matlab code 5` box, they precisely do RMS of RMS values from windows.
